// Code generated by generate-elems.sh. DO NOT EDIT.

package html

func A(nodes ...Node) ElemNode {
	return Elem("a", nodes...)
}

func P(nodes ...Node) ElemNode {
	return Elem("p", nodes...)
}

func DIV(nodes ...Node) ElemNode {
	return Elem("div", nodes...)
}

func FORM(nodes ...Node) ElemNode {
	return Elem("form", nodes...)
}

func INPUT(nodes ...Node) ElemNode {
	return Elem("input", nodes...)
}

func BUTTON(nodes ...Node) ElemNode {
	return Elem("button", nodes...)
}

func BODY(nodes ...Node) ElemNode {
	return Elem("body", nodes...)
}

func HEAD(nodes ...Node) ElemNode {
	return Elem("head", nodes...)
}

func HTML(nodes ...Node) ElemNode {
	return Elem("html", nodes...)
}

func META(nodes ...Node) ElemNode {
	return Elem("meta", nodes...)
}

func LINK(nodes ...Node) ElemNode {
	return Elem("link", nodes...)
}

func TITLE(nodes ...Node) ElemNode {
	return Elem("title", nodes...)
}

func NAV(nodes ...Node) ElemNode {
	return Elem("nav", nodes...)
}

func SVG(nodes ...Node) ElemNode {
	return Elem("svg", nodes...)
}

func USE(nodes ...Node) ElemNode {
	return Elem("use", nodes...)
}

func TABLE(nodes ...Node) ElemNode {
	return Elem("table", nodes...)
}

func TH(nodes ...Node) ElemNode {
	return Elem("th", nodes...)
}

func TR(nodes ...Node) ElemNode {
	return Elem("tr", nodes...)
}

func TD(nodes ...Node) ElemNode {
	return Elem("td", nodes...)
}

func IMG(nodes ...Node) ElemNode {
	return Elem("img", nodes...)
}

func UL(nodes ...Node) ElemNode {
	return Elem("ul", nodes...)
}

func LI(nodes ...Node) ElemNode {
	return Elem("li", nodes...)
}

func OL(nodes ...Node) ElemNode {
	return Elem("ol", nodes...)
}

func BR(nodes ...Node) ElemNode {
	return Elem("br", nodes...)
}

func B(nodes ...Node) ElemNode {
	return Elem("b", nodes...)
}

func I(nodes ...Node) ElemNode {
	return Elem("i", nodes...)
}

func H1(nodes ...Node) ElemNode {
	return Elem("h1", nodes...)
}

func H2(nodes ...Node) ElemNode {
	return Elem("h2", nodes...)
}

func H3(nodes ...Node) ElemNode {
	return Elem("h3", nodes...)
}

func H4(nodes ...Node) ElemNode {
	return Elem("h4", nodes...)
}

func H5(nodes ...Node) ElemNode {
	return Elem("h5", nodes...)
}

func H6(nodes ...Node) ElemNode {
	return Elem("h6", nodes...)
}

func SPAN(nodes ...Node) ElemNode {
	return Elem("span", nodes...)
}

