#!/usr/bin/env bash
set -euo pipefail

elements="a p div form input button body head html meta link title nav svg use table th tr td img ul li ol br b i h1 h2 h3 h4 h5 h6 span"
tmp=$(mktemp)
output=$1

function writeln {
    printf "$1\n" >> $tmp
}

writeln "// Code generated by generate-elems.sh. DO NOT EDIT."
writeln ""
writeln "package $GOPACKAGE"
writeln ""

for elem in $elements; do
    writeln "func ${elem^^}(nodes ...Node) ElemNode {"
    writeln "\treturn Elem(\"${elem}\", nodes...)"
    writeln "}"
    writeln ""
done

mv $tmp $output
